### ISSUE TITLE
the --verbose argument in the cli

### ISSUE THREAD

**Issue by arademaker** [delph-in/delphin.edm#2]
Documentation output of `delphin edm -h` could be more explicit about the use of repeated `v` to increase the verbosity. I didn't find the definition of this parameter in the cli module, maybe this came from pydelphin?

**Comment by goodmami** [comment]
Yes it's from PyDelphin. All commands have the option, and it increases the logging level (`-v` == warning, `-vv` == info, `-vvv` == debug). I agree that PyDelphin's `--help` output could more clearly describe this. For this delphin.edm project, I think some description in the README should be sufficient.

**Comment by arademaker** [comment]
In the end of the section `usage` of the README.md I see the information about the `-v`. I may have missed that before. I belive this issue can be closed.

**Comment by goodmami** [comment]
Ok thanks
